/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "mux_2x1.v:1.1-7.10" *)
module mux_2x1(a, b, sel, out);
  (* src = "mux_2x1.v:2.8-2.9" *)
  input a;
  wire a;
  (* src = "mux_2x1.v:3.8-3.9" *)
  input b;
  wire b;
  (* src = "mux_2x1.v:4.8-4.11" *)
  input sel;
  wire sel;
  (* src = "mux_2x1.v:5.9-5.12" *)
  output out;
  wire out;
  wire _0_;
  wire _1_;
  INVX1 _2_ (
    .A(a),
    .Y(_0_)
  );
  NAND2X1 _3_ (
    .A(b),
    .B(sel),
    .Y(_1_)
  );
  OAI21X1 _4_ (
    .A(_0_),
    .B(sel),
    .C(_1_),
    .Y(out)
  );
endmodule
